- README.md
> Test to make sure Becky can push

- .gitignore
- client/main.jsx
- imports/api/landing/server/publications.js
- imports/api/landing/server/users.js
- imports/api/landing/users.js
- imports/api/message/messageRooms.js
- imports/api/message/messages.js
- imports/api/message/server/messageRooms.js
- imports/api/message/server/messages.js
- imports/api/profile/images.js
- imports/api/profile/server/images.js
- imports/api/profile/server/publications.js
- imports/startup/client/index.js
- imports/startup/server/index.js
- server/main.js
> [DS] file structure and model update

- .meteor/packages
- .meteor/versions
- client/main.html
- imports/ui/components/message_room_card.jsx
- imports/ui/components/message_room_card.test.jsx
- imports/ui/components/message_rooms_popout.jsx
- imports/ui/layouts/App.jsx
- imports/ui/layouts/App.test.jsx
- package.json
message room pop-out component. Front-end with unit test
> [DS] message room popout

- imports/api/control/control.js
- imports/api/image/images.js
- imports/api/image/server/publications.js
- imports/api/message/messageRooms.js
- imports/api/message/messages.js
- imports/startup/client/index.js
- imports/startup/server/index.js
- imports/ui/components/message_rooms_popout.jsx
- server/main.js
import re-structure  
global Models, Controllers
update file structure
> [DS] update file structure, import re-structure, global Models, Controllers

- .meteor/packages
- client/_color_var.scss
- client/main.scss
- imports/api/control/control.js
- imports/api/message/messages.js
- imports/ui/components/message_room_card.test.jsx
- imports/ui/components/message_text.jsx
- imports/ui/pages/Discover.jsx
- imports/ui/pages/Message.jsx
- imports/ui/pages/Profile.jsx
> [DS] message room front

- imports/ui/pages/Landing.jsx
Tested that when a user is logged in, the button for logout displays
Texted that when a user is logged out, the button for logout does NOT display
> [GL] updated landing page to hide logout if user is not logged in

- imports/api/control/control.js
- imports/startup/server/fixtures.js
- imports/startup/server/index.js
This change will populate the discover page with users upon startup.
> gleake user creation

- imports/ui/components/message_rooms_popout.test.jsx
Popout message testing scenario
> popout message test scenario

- client/main.scss
- imports/ui/components/discover_card.jsx
updated the discover page to organize it in the form of grids
> updated to discover grids in discover page

- imports/ui/components/discover_card.jsx
- imports/ui/pages/Discover.jsx
> [DS] Discover page grid

- imports/ui/components/profile_card.jsx
added default text to make it clear how to edit the profile / initially set a summary for a brand new user.  Created & Updated task in Pivotal Tracker
> updated profile edit page

- imports/startup/server/index.js
> updated the spelling error

- imports/ui/components/message_rooms_popout.test.jsx
Removed console logs statements
> updated to remove console logs

- imports/startup/server/accounts-config.js
As a part of learning process, added comments to explain account_config
> Added comments to explain account_config

- imports/ui/components/message_rooms_popout.test.jsx
updated to test object ids, clean up comments
> updated test class

- .eslintrc.js
- imports/ui/components/message_rooms_popout.test.jsx
- package.json
Validated 0 impact to existing code & application.  
Validated can run esLint on a javascript file via console.
> Gl linting

- imports/api/control/control.js
- imports/api/image/images.js
- imports/api/message/messageRooms.js
- imports/api/user/users.js
- imports/startup/client/index.js
- imports/ui/components/discover_card.jsx
- imports/ui/components/message_room_card.jsx
- imports/ui/components/message_rooms_popout.jsx
- imports/ui/components/message_text.jsx
- imports/ui/components/profile_card.jsx
- imports/ui/pages/Discover.jsx
- imports/ui/pages/Message.jsx
- imports/ui/pages/Profile.jsx
> [DS] router msg

- .meteor/packages
- imports/api/control/control.js
- imports/api/message/messages.js
- imports/api/message/server/methods.js
- imports/api/message/server/publications.js
- imports/startup/server/index.js
- imports/ui/components/message_text.jsx
- imports/ui/pages/Message.jsx
1. Add Publication for MessageRoom
2. Move msgRoom outside of control js because this shouldn't be here due to separation of concerns. The messageroom should be passed in as argument so that anyone who wants to send a message who subscribes to MessageRoom can pass it in.  
3. Call the meteor method for creating a message - this now uses the check security package to validate the types are correct.
4. Update allow statement for security - you should not be able to insert if you don't have a userId
5. index needs to import the new methods.js to support meteor methods
6. Add loading for the MessageRooms - the createContainer should wait until the MessageRoom is loaded on the client before returning.  This will prevent loading errors.
> Gl securityfix2

- imports/api/control/control.js
- imports/api/message/messageRooms.js
- imports/api/message/messages.js
- imports/api/message/server/methods.js
- imports/api/user/server/methods.js
- imports/ui/pages/Message.jsx
added meteor method call for editing profile
validated that it works
> Gl securityfix7 editprofile

- imports/startup/server/accounts-config.js
> updated the config file

- .meteor/packages
- .meteor/versions
Just re-adding for the demo tomorrow for functionality purposes.
> TEMPORARILY re-add autopublish for demo - to fix message room bug

- imports/startup/server/accounts-config.js
- imports/ui/components/discover_card.jsx
- imports/ui/components/message_rooms_popout.jsx
- imports/ui/components/profile_card.jsx
- imports/ui/pages/Discover.jsx
- imports/ui/pages/Profile.jsx
fix landing logout 
className 
etc
> [DS] small fix for landing logout etc

- .meteor/packages
- .meteor/versions
- imports/api/control/control.js
- imports/api/message/server/publications.js
- imports/ui/components/discover_card.jsx
- imports/ui/components/message_rooms_popout.jsx
- imports/ui/pages/Message.jsx
Test plan: First drop messageroom and message collections to start clean
1. Validate that when messaging a user from the discover page for the first time, the message sends successfully.
1a. Validate that the message shows up in the MessageRoomPopout
1b. Message the same user again, validate the newer message shows up in the MessageRoomPopout
2. Message a second user and validate their message is added to MessageRoomPopout
Repeated for multiple users
> fix popout by adding composite publish

- imports/ui/components/message_text.test.jsx
- imports/ui/components/profile_card.test.jsx
> more test cases
